#ifndef C_PROJECT_ALGEBRAFUN_TEST_H
#define C_PROJECT_ALGEBRAFUN_TEST_H
int matrixPow_Test();
int sumMatrixRows_Test();
int elemGreaterThanValue_Test();
int elemLowerThanValue_Test();
int absArray_Test();
int any_Test();
int truesInArray_Test();
int crossProductArray_Test();
int getColumn_Test();
int crossProductMatrix_Test();
int getTrueColumns_Test();
int arrayDotProduct_Test();
int matrixDotProduct_Test();
int generateIntegerArray_Test();
int generateOnesArray_Test();
int timesArrayMatrix_Test();
int substractMatrixs_Test();
int dividesArrayMatrix_Test();
int getRows_Test();
int multiplyMatrixByScalar_Test();
int getRow_Test();
int multiplyMatrixs_Test();
#endif //C_PROJECT_ALGEBRAFUN_TEST_H
